name: Model Training Pipeline

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    build-and-train:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .

            - name: Run Pipeline
              run: |
                  python src/pipeline.py
            
            - name: Run Train
              run: |
                  python src/train.py

            - name: Upload model artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: tip-prediction-model
                  path: models/
              